### ISSUE TITLE
Included libfftw3.a and libewavelet.a static libs are macOS only

### ISSUE THREAD

**Issue by Eximius** [fastlib/fCWT#15] opened 2022-12-13 11:59 UTC
libfftw3.a and libwavelet.a are Mach-O objects, so practically only compatible with MacOS and not UNIX... Probably worth noting this in the readme and adding links to the source (+hash for reproducibility).

```
fCWT/src/libwavelib on  main [!] via C v12.2.0-gcc 🔋⚡ 42% ❯ ar x libwavelib.a 

fCWT/src/libwavelib on  main [!?] via C v12.2.0-gcc 🔋⚡ 42% ❯ ls
conv.o  cwt.o  cwtmath.o  hsfft.o  libwavelib.a  real.o  wavefilt.o  wavefunc.o  wavelib.h  wavelib.lib  wavelib.o  wtmath.o

fCWT/src/libwavelib on  main [!?] via C v12.2.0-gcc 🔋⚡ 42% ❯ file *.o
conv.o:     Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
cwt.o:      Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
cwtmath.o:  Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
hsfft.o:    Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
real.o:     Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
wavefilt.o: Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
wavefunc.o: Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
wavelib.o:  Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
wtmath.o:   Mach-O 64-bit x86_64 object, flags:<|SUBSECTIONS_VIA_SYMBOLS>
```

**Comment by fastlib** [comment] 2022-12-19 10:47
Thank you for noting this. This is probably the cause why people are having trouble building fCWT on Linux. I will compile libraries for Linux and will add self-compiling instructions to the readme.

**Comment by fastlib** [comment] 2023-01-14 19:12
Fixed in the current version. I'll close this issue.

**Closed** 2023-01-14 19:12 UTC
